import AllCategory from "@/components/AllCategory";
import MainNav from "@/components/MainNav";
import Settings from "@/components/Settings";
import SideNav from "@/components/SideNav";
import { Inter } from "next/font/google";
import { CiSearch } from "react-icons/ci";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dua & Ruqyah",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch("https://dua-backend-mu.vercel.app/api/v1/dua");
  const dua = await res.json();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex ">
          <div className="w-[100px] mt-6 ml-7 flex flex-col gap-y-5  bg-white rounded-3xl px-4  pb-16 items-center">
            <SideNav></SideNav>
          </div>
          <div className="min-w-[calc(100%-120px)]">
            <MainNav></MainNav>
            <div className="ml-3 grid grid-cols-12 mt-3 bg-white">
              <div className="col-span-3 lg:px-7 ">
                <div className="px-5 h-14 bg-[#1fa45b] rounded-t-md flex justify-center flex-col gap-4 items-center rounded-t-1">
                  <p className="text-base text-center px-5 text-white mx-auto">
                    Categories
                  </p>
                </div>
                <div className="mt-3">
                  <form action="" className="relative">
                    <input
                      className="h-12 placeholder:text-mute-grey placeholder:text-sm border-[1px] block bg-white w-full rounded-md pl-12 shadow-sm focus:outline-none focus:border-primary focus:ring-primary focus:ring-1  
        "
                      type="text"
                      placeholder="Search Categories"
                    />
                    <button className="absolute top-1 left-1 p-2 bg-gray-100 rounded">
                      <CiSearch className="text-xl font-bold "></CiSearch>
                    </button>
                  </form>
                </div>
                <div className="mt-3">
                  <AllCategory />
                </div>
              </div>
              <div className="col-span-7 mx-3">{children}</div>
              <div className="col-span-2 ">
                <Settings />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
